package xpz

import (
	"testing"

	"github.com/rubensantoniorosa2704/gxdocgen/internal/model"
)

func TestDeterminePackage_FromAnnotation(t *testing.T) {
	doc := &model.DocComment{
		Package: "users",
	}
	
	result := determinePackage(doc, "SomeParent", "GetUser")
	
	if result != "users" {
		t.Errorf("Expected 'users', got '%s'", result)
	}
}

func TestDeterminePackage_FromTag(t *testing.T) {
	doc := &model.DocComment{
		Tags: []string{"authentication", "security"},
	}
	
	result := determinePackage(doc, "", "LoginUser")
	
	if result != "authentication" {
		t.Errorf("Expected 'authentication', got '%s'", result)
	}
}

func TestDeterminePackage_FromParent(t *testing.T) {
	doc := &model.DocComment{}
	
	result := determinePackage(doc, "Customers", "InsertCustomer")
	
	if result != "Customers" {
		t.Errorf("Expected 'Customers', got '%s'", result)
	}
}

func TestDeterminePackage_InferredFromName(t *testing.T) {
	tests := []struct {
		name     string
		procName string
		expected string
	}{
		{"CamelCase", "CustomerInsert", "customer"},
		{"With prefix", "UserDelete", "user"},
	}
	
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := &model.DocComment{}
			result := determinePackage(doc, "", tt.procName)
			
			if result != tt.expected {
				t.Errorf("For %s, expected '%s', got '%s'", tt.procName, tt.expected, result)
			}
		})
	}
}

func TestDeterminePackage_Root(t *testing.T) {
	doc := &model.DocComment{}
	
	// Test with a name that can't be inferred
	result := determinePackage(doc, "", "lowercase")
	
	if result != "Root" {
		t.Errorf("Expected 'Root', got '%s'", result)
	}
}

func TestInferPackageFromName(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"CustomerInsert", "customer"},
		{"UserDelete", "user"},
		{"prLoadData", "load"},
		{"pr_GetInfo", "get"},
		{"APICallHandler", "apic"}, // Matches APIC (capitals before lowercase)
		{"simple", ""},
		{"ALLCAPS", "allcaps"}, // All capitals become lowercase
	}
	
	for _, tt := range tests {
		result := inferPackageFromName(tt.input)
		if result != tt.expected {
			t.Errorf("inferPackageFromName(%q) = %q, expected %q", tt.input, result, tt.expected)
		}
	}
}

func TestDetermineSummary_FromAnnotation(t *testing.T) {
	doc := &model.DocComment{
		Summary: "Creates a new user",
	}
	
	result := determineSummary(doc, "InsertUser")
	
	if result != "Creates a new user" {
		t.Errorf("Expected 'Creates a new user', got '%s'", result)
	}
}

func TestDetermineSummary_InferredFromName(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"InsertUser", "Insert User"},
		{"GetUserByID", "Get User By ID"},
		{"DeleteCustomer", "Delete Customer"},
		{"APIHandler", "API Handler"},
		{"LoadData", "Load Data"},
	}
	
	for _, tt := range tests {
		doc := &model.DocComment{}
		result := determineSummary(doc, tt.input)
		
		if result != tt.expected {
			t.Errorf("For %s, expected '%s', got '%s'", tt.input, tt.expected, result)
		}
	}
}

func TestDetermineSummary_AutoGenerated(t *testing.T) {
	doc := &model.DocComment{}
	
	// For lowercase name, inferSummaryFromName returns the name as-is
	result := determineSummary(doc, "unknownformat")
	
	expected := "unknownformat" // Inference returns as-is for non-CamelCase
	if result != expected {
		t.Errorf("Expected '%s', got '%s'", expected, result)
	}
}

func TestDetermineDescription_FromAnnotation(t *testing.T) {
	doc := &model.DocComment{
		Description: "This procedure creates a user",
	}
	
	result := determineDescription(doc, "InsertUser", "Insert User")
	
	if result != "This procedure creates a user" {
		t.Errorf("Expected annotation description, got '%s'", result)
	}
}

func TestDetermineDescription_AutoGenerated(t *testing.T) {
	doc := &model.DocComment{}
	
	result := determineDescription(doc, "InsertUser", "")
	
	expected := "Auto-generated description for InsertUser. Add @description to improve this."
	if result != expected {
		t.Errorf("Expected '%s', got '%s'", expected, result)
	}
}

func TestInferSummaryFromName(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"InsertUser", "Insert User"},
		{"GetUserByID", "Get User By ID"},
		{"DeleteCustomer", "Delete Customer"},
		{"LoadDataFromAPI", "Load Data From API"},
		{"simpletest", "simpletest"},
		{"API", "API"},
		{"HTTPRequest", "HTTP Request"},
	}
	
	for _, tt := range tests {
		result := inferSummaryFromName(tt.input)
		if result != tt.expected {
			t.Errorf("inferSummaryFromName(%q) = %q, expected %q", tt.input, result, tt.expected)
		}
	}
}
